[package]
name = "xv7-fs"
version = "0.1.0"
authors = ["imlk <imlk.geek@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
